[package]
name = "aoc2022-x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_auto = {path="../aoc_auto"}
nom = "7.1.1"
