[package]
name = "aoc2022-4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_auto = {path="../aoc_auto"}
gcollections = "1.5.0"
intervallum = "1.4.0"
nom = "7.1.1"
