[package]
name = "aoc-auto"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
reqwest = {version = "0.11.13", features = ["blocking", "cookies"]}


